import type { Player } from '../types/Player';
import { REWARDS } from '../config/economy';
const KEY = 'aroncandy:progress:v1';
const integer = (v: unknown, fallback: number, max = 1e9) => typeof v === 'number' && Number.isFinite(v) ? Math.max(0, Math.min(max, Math.floor(v))) : fallback;
const numbers = (v: unknown) => Object.fromEntries(Object.entries(v && typeof v === 'object' ? v : {}).filter(([k]) => /^\d+$/.test(k)).map(([k, n]) => [k, integer(n, 0)]));
export function newPlayer(): Player { return { version: 1, playerId: typeof crypto !== 'undefined' ? crypto.randomUUID() : 'guest', username: 'Candy Explorer', currentLevel: 1, unlockedLevels: 1, stars: {}, highScores: {}, coins: 250, lives: 5, livesUpdatedAt: Date.now(), boosters: { hammer: 3, shuffle: 2, rainbow: 1 }, settings: { music: true, sfx: true, volume: .45, reducedMotion: false }, lastReward: '', updatedAt: Date.now() }; }
export function sanitizePlayer(value: unknown): Player { const d = newPlayer(); if (!value || typeof value !== 'object') return d; const p = value as Partial<Player>; return { ...d, playerId: typeof p.playerId === 'string' ? p.playerId : d.playerId, username: typeof p.username === 'string' ? p.username.slice(0, 24) : d.username, currentLevel: Math.max(1, integer(p.currentLevel, 1, 100)), unlockedLevels: Math.max(1, integer(p.unlockedLevels, 1, 100)), stars: numbers(p.stars), highScores: numbers(p.highScores), coins: integer(p.coins, 250), lives: integer(p.lives, 5, 5), livesUpdatedAt: Math.min(Date.now(), integer(p.livesUpdatedAt, Date.now(), Number.MAX_SAFE_INTEGER)), boosters: { hammer: integer(p.boosters?.hammer, 3), shuffle: integer(p.boosters?.shuffle, 2), rainbow: integer(p.boosters?.rainbow, 1) }, settings: { music: p.settings?.music !== false, sfx: p.settings?.sfx !== false, volume: typeof p.settings?.volume === 'number' ? Math.max(0, Math.min(1, p.settings.volume)) : .45, reducedMotion: p.settings?.reducedMotion === true }, lastReward: typeof p.lastReward === 'string' ? p.lastReward : '', updatedAt: integer(p.updatedAt, Date.now(), Number.MAX_SAFE_INTEGER) }; }
export function refillLives(p: Player, now = Date.now()): Player { if (p.lives >= 5) return p; const gained = Math.floor((now - p.livesUpdatedAt) / 1800000); return gained > 0 ? { ...p, lives: Math.min(5, p.lives + gained), livesUpdatedAt: p.livesUpdatedAt + gained * 1800000 } : p; }
export function loadProgress(): { player: Player; warning?: string } { try { const raw = localStorage.getItem(KEY); return { player: refillLives(raw ? sanitizePlayer(JSON.parse(raw)) : newPlayer()) }; } catch { return { player: newPlayer(), warning: 'Penyimpanan browser tidak tersedia. Progres hanya berlaku selama sesi ini.' }; } }
export function saveProgress(p: Player): boolean { try { localStorage.setItem(KEY, JSON.stringify(p)); return true; } catch { return false; } }
export function winProgress(p: Player, level: number, score: number, stars: number): Player { const first = !p.stars[level]; return { ...p, currentLevel: Math.min(100, level + 1), unlockedLevels: Math.max(p.unlockedLevels, Math.min(100, level + 1)), highScores: { ...p.highScores, [level]: Math.max(p.highScores[level] ?? 0, score) }, stars: { ...p.stars, [level]: Math.max(p.stars[level] ?? 0, stars) }, coins: p.coins + (first ? REWARDS.levelComplete + stars * REWARDS.perStar + (stars >= 3 ? REWARDS.threeStarBonus : 0) + REWARDS.firstClear : REWARDS.replay), updatedAt: Date.now() }; }
export const loseLife = (p: Player): Player => ({ ...p, lives: Math.max(0, p.lives - 1), livesUpdatedAt: p.lives === 5 ? Date.now() : p.livesUpdatedAt, updatedAt: Date.now() });
