import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Game } from '../src/game/Game';
import { LEVELS,getLevel } from '../src/levels';
import { detectMatches } from '../src/game/MatchDetector';
import { possibleMoves } from '../src/game/HintSystem';
import { specialFor,specialCombination } from '../src/game/SpecialCandySystem';
import { gravity,dropItems } from '../src/game/GravitySystem';
import { hitBlockers } from '../src/game/BlockerSystem';
import { shuffle } from '../src/game/ShuffleSystem';
import { SpawnSystem } from '../src/game/SpawnSystem';
import { cloneBoard } from '../src/game/Board';
import { canSwap } from '../src/game/SwapManager';
import { refillLives,newPlayer,sanitizePlayer,winProgress } from '../src/services/progress';
import type { Board } from '../src/types/Candy';
const empty=():Board=>Array.from({length:9},()=>Array.from({length:9},()=>null));
const lineBoard=(rows:number[][]):Board=>{const b=empty();let id=0;rows.forEach((rr,r)=>rr.forEach((color,c)=>b[r][c]={candy:{id:++id,color}}));return b;};
test('all 20 configurations: no initial matches, legal moves, valid masks and achievable color targets across 600 boards',()=>{
 for(const level of LEVELS){for(const o of level.objectives)if(o.type==='collect')assert.ok(o.color!<level.candyTypes);
  for(let seed=1;seed<=30;seed++){const g=new Game(level,seed);assert.equal(g.phase,'IDLE',`level ${level.id} seed ${seed}`);assert.equal(detectMatches(g.board).length,0);assert.ok(possibleMoves(g.board).length>0);g.board.forEach((rr,r)=>rr.forEach((v,c)=>assert.equal(!!v,!!level.board[r][c])));}
 }
});
test('diagonal, distant and blocker swaps are rejected without spending moves',async()=>{const g=new Game(getLevel(5),13);const before=g.snapshot();assert.deepEqual(await g.act({type:'swap',a:{r:3,c:3},b:{r:4,c:4}}),[]);assert.deepEqual(await g.act({type:'swap',a:{r:3,c:3},b:{r:3,c:5}}),[]);for(const b of g.level.blockers)assert.equal(canSwap(g.board,b,{r:b.r,c:b.c+1}),false);assert.equal(g.moves,before.moves);assert.deepEqual(g.board,before.board);});
test('invalid adjacent swap animates then returns exactly to its original board',async()=>{const g=new Game(getLevel(1),87);const valid=possibleMoves(g.board);for(let r=0;r<9;r++)for(let c=0;c<8;c++){const a={r,c},b={r,c:c+1};if(valid.some(([x,z])=>x.r===r&&x.c===c&&z.r===b.r&&z.c===b.c))continue;const before=cloneBoard(g.board),moves=g.moves;const frames=await g.act({type:'swap',a,b});assert.equal(frames[0].phase,'SWAPPING');assert.equal(frames.at(-1)?.phase,'IDLE');assert.deepEqual(g.board,before);assert.equal(g.moves,moves);assert.equal(g.actions.length,0);return;}assert.fail('No invalid swap found');});
test('4, 5 and connected T/L patterns create the correct special',()=>{assert.equal(specialFor(detectMatches(lineBoard([[0,0,0,0]]))[0]),'striped-h');assert.equal(specialFor(detectMatches(lineBoard([[0,0,0,0,0]]))[0]),'bomb');const b=lineBoard([[1,0,2],[0,0,0],[2,0,1]]);const matches=detectMatches(b);assert.equal(matches.length,1);assert.equal(matches[0].cells.length,5);assert.equal(specialFor(matches[0]),'wrapped');});
test('gravity respects gaps and fixed blockers and preserves surviving identities',()=>{const b=empty();for(const r of [0,1,3,4,5,6,7,8])b[r][0]={candy:null};b[0][0]!.candy={id:100,color:0};b[3][0]!.candy={id:101,color:1};b[5][0]!.blocker={kind:'stone',hp:2,maxHp:2};b[6][0]!.candy={id:102,color:2};gravity(b,new SpawnSystem(1,6));assert.equal(b[1][0]!.candy!.id,100);assert.equal(b[4][0]!.candy!.id,101);assert.equal(b[8][0]!.candy!.id,102);assert.equal(b[2][0],null);assert.equal(b[5][0]!.candy,null);});
test('ice cracks, blocker adjacency and objectives count once',()=>{const b=lineBoard([[0,1,2],[1,2,0],[2,0,1]]);b[1][1]!.blocker={kind:'ice',hp:2,maxHp:2};b[1][2]!.blocker={kind:'box',hp:1,maxHp:1};b[1][2]!.candy=null;const goals=[{type:'breakIce' as const,current:0,amount:1},{type:'breakBlockers' as const,current:0,amount:1,blocker:'box' as const}];hitBlockers(b,new Set(['1,1']),goals);assert.equal(b[1][1]!.blocker?.hp,1);assert.equal(goals[0].current,0);assert.equal(goals[1].current,1);hitBlockers(b,new Set(['1,1']),goals);assert.equal(goals[0].current,1);assert.equal(b[1][1]!.blocker,undefined);hitBlockers(b,new Set(['1,1']),goals);assert.equal(goals[0].current,1);});
test('color bomb + normal clears exactly the target color and the bomb',()=>{const b=lineBoard([[0,1,2],[1,2,0],[2,0,1]]);b[0][0]!.candy!.special='bomb';const hits=specialCombination(b,{r:0,c:0},{r:0,c:1});assert.deepEqual([...hits].sort(),['0,0','0,1','1,0','2,2']);});
test('all special combinations activate with bounded board coordinates',()=>{for(const pair of [['striped-h','striped-v'],['striped-h','wrapped'],['wrapped','wrapped'],['bomb','striped-h'],['bomb','bomb']] as const){const g=new Game({...getLevel(1),board:Array.from({length:9},()=>Array(9).fill(1))},2);g.board[4][4]!.candy!.special=pair[0];g.board[4][5]!.candy!.special=pair[1];const hits=specialCombination(g.board,{r:4,c:4},{r:4,c:5});assert.ok(hits.size>=9);assert.ok(hits.size<=81);if(pair[0]==='bomb'&&pair[1]==='bomb')assert.equal(hits.size,81);}});
test('shuffle preserves blockers/items and leaves no matches and a playable move',()=>{const g=new Game(getLevel(17),123);const before=cloneBoard(g.board);assert.equal(shuffle(g.board,new SpawnSystem(19,6)),true);assert.equal(detectMatches(g.board).length,0);assert.ok(possibleMoves(g.board).length);before.forEach((rr,r)=>rr.forEach((v,c)=>{if(v?.blocker)assert.deepEqual(g.board[r][c]?.blocker,v.blocker);if(v?.candy?.item)assert.deepEqual(g.board[r][c]?.candy,v.candy);}));});
test('drop items count only at the actual bottom of a column',()=>{const b=empty();b[4][0]={candy:{id:1,color:0,item:true}};b[8][0]={candy:{id:2,color:0}};assert.equal(dropItems(b),0);b[8][0]!.candy={id:3,color:0,item:true};assert.equal(dropItems(b),1);assert.ok(b[4][0]!.candy);});
test('one hit on layered ice consumes the candy and refills under the surviving layer',async()=>{const level={...getLevel(1),board:Array.from({length:9},()=>Array(9).fill(1)),blockers:[{r:4,c:4,kind:'ice' as const,hp:2}],objectives:[{type:'breakIce' as const,amount:1}]};const g=new Game(level,33),original=g.board[4][4]!.candy!.id;const frames=await g.act({type:'hammer',at:{r:4,c:4}}),destroyed=frames.find(f=>f.phase==='DESTROYING')!;assert.equal(destroyed.board[4][4]!.blocker!.hp,1);assert.equal(destroyed.board[4][4]!.candy,null);const fallen=frames.find(f=>f.phase==='FALLING')!;assert.notEqual(fallen.board[4][4]!.candy!.id,original);assert.equal(fallen.board[4][4]!.blocker!.hp,1);});
test('valid moves cascade to stability, decrease moves once, and replay deterministically',async()=>{for(const level of LEVELS)for(let seed=1;seed<=4;seed++){const g=new Game(level,seed),replay=new Game(level,seed);let actions=0;while(g.phase==='IDLE'&&actions<80){const choices=possibleMoves(g.board);assert.ok(choices.length);const [a,b]=choices[(seed+actions)%choices.length];const moves=g.moves;await g.act({type:'swap',a,b});await replay.act({type:'swap',a,b});if(!(g.phase as string).startsWith('WIN'))assert.equal(g.moves,moves-1);assert.equal(g.score,replay.score);assert.deepEqual(g.board,replay.board);if(g.phase==='IDLE'){assert.equal(detectMatches(g.board).length,0);assert.ok(possibleMoves(g.board).length);}assert.notEqual(g.phase,'ERROR');actions++;}assert.ok(['WIN','LOSE'].includes(g.phase));}});
test('boosters spend no moves, wins require all objectives, and terminal games reject input',async()=>{const level={...getLevel(1),moves:1,objectives:[{type:'score' as const,amount:999999},{type:'collect' as const,color:0,amount:1}]};const g=new Game(level,1);const n=g.moves;await g.act({type:'hammer',at:{r:0,c:0}});assert.equal(g.moves,n);assert.equal(g.phase,'IDLE');const [a,b]=g.hint()!;await g.act({type:'swap',a,b});assert.equal(g.phase,'LOSE');assert.deepEqual(await g.act({type:'shuffle'}),[]);const win=new Game({...getLevel(1),objectives:[{type:'score',amount:1}]},2);const [x,z]=win.hint()!;await win.act({type:'swap',a:x,b:z});assert.equal(win.phase,'WIN');});
test('saved progress tolerates corruption and lives refill without exceeding five',()=>{const p=sanitizePlayer({lives:-5,coins:'oops',unlockedLevels:900,settings:{volume:9}});assert.equal(p.lives,0);assert.equal(p.coins,250);assert.equal(p.unlockedLevels,100);assert.equal(p.settings.volume,1);const base={...newPlayer(),lives:1,livesUpdatedAt:1000};assert.equal(refillLives(base,1000+1800000*8).lives,5);const won=winProgress(newPlayer(),1,3000,2);assert.equal(won.unlockedLevels,2);assert.equal(winProgress(won,1,100,1).highScores[1],3000);});
