'use client';
import { useEffect,useState } from 'react';
import { Play,Settings,Trophy,Heart,Coins,Sparkles,Gift,UserRound,ArrowRight,Volume2,Music,Check,LogOut,Mail,Flower2,ShieldCheck,CloudOff,Lightbulb } from 'lucide-react';
import type { Player } from '@/types/Player';
import type { Frame } from '@/game/Game';
import type { LevelConfig } from '@/types/Level';
import type { AudioManager } from '@/game/AudioManager';
import { WORLDS } from '@/levels';
import { starsFor } from '@/game/ScoreSystem';
import { database } from '@/services/database';
import { signIn,signOut,signUp,signInWithPassword } from '@/services/auth';
import { getLeaderboard,type LeaderboardEntry } from '@/services/leaderboard';
import Modal from './Modal';
import Objective from './Objective';
import PauseMenu from './PauseMenu';
import WinModal from './WinModal';
import LoseModal from './LoseModal';
export type Dialog='intro'|'pause'|'settings'|'leaderboard'|'profile'|'daily'|'help'|'lives'|'quit'|'win'|'lose'|'error'|null;
interface Props{modal:Dialog;player:Player;frame:Frame|null;level:LevelConfig;busy:boolean;clock:number;sessionEmail:string;quitTarget:'map'|'retry';onClose:()=>void;onOpen:(d:Dialog)=>void;onStart:()=>void;onNext:()=>void;onMap:()=>void;onRetry:()=>void;onQuit:()=>void;onConfirmQuit:()=>void;updatePlayer:(p:Player|((p:Player)=>Player))=>void;notify:(text:string)=>void;audio:AudioManager|null;onSignOut:()=>void}
const dayKey=()=>new Date().toLocaleDateString('en-CA');
const fmt=(n:number)=>n.toLocaleString('id-ID');
export default function GameDialogs({modal,player,frame,level,busy,clock,sessionEmail,quitTarget,onClose,onOpen,onStart,onNext,onMap,onRetry,onQuit,onConfirmQuit,updatePlayer,notify,audio,onSignOut}:Props){
 const [username,setUsername]=useState(player.username),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMode,setAuthMode]=useState<'login'|'register'>('login'),[authBusy,setAuthBusy]=useState(false),[leaderboard,setLeaderboard]=useState<LeaderboardEntry[]>([]),[leaderboardStatus,setLeaderboardStatus]=useState('');
 useEffect(()=>{if(modal==='profile')setUsername(player.username);},[modal,player.username]);
 useEffect(()=>{if(modal!=='leaderboard')return;if(!database()){setLeaderboardStatus('Peringkat online belum tersedia. Rekor pribadimu ada di bawah.');return;}let active=true;setLeaderboardStatus('Memuat peringkat…');getLeaderboard().then(rows=>{if(active){setLeaderboard(rows);setLeaderboardStatus(rows.length?'':'Belum ada skor terverifikasi. Jadilah yang pertama!');}}).catch(()=>{if(active)setLeaderboardStatus('Peringkat belum dapat dimuat. Coba lagi nanti.');});return()=>{active=false;};},[modal]);
 const setting=(field:keyof Player['settings'],value:boolean|number)=>updatePlayer(p=>({...p,settings:{...p.settings,[field]:value},updatedAt:Date.now()}));
 const claimDaily=()=>{if(player.lastReward===dayKey())return;updatePlayer(p=>({...p,lastReward:dayKey(),coins:p.coins+100,boosters:{...p.boosters,hammer:p.boosters.hammer+1},updatedAt:Date.now()}));audio?.play('win');notify('100 koin + 1 hammer masuk ke tasmu!');};
 const refillMinutes=Math.max(1,Math.ceil((1800000-(clock-player.livesUpdatedAt)%1800000)/60000));
 if(!modal)return null;
 return <Modal title={modal} onClose={busy?()=>{}:onClose} className={modal==='leaderboard'?'wide-modal':''}>
 {modal==='intro'&&<><span className="modal-emblem"><Flower2/></span><span className="eyebrow">{WORLDS[level.world].name}</span><h2>Level {level.id}</h2><p className="level-name">{level.name}</p><Objective objectives={level.objectives.map(o=>({...o,current:0}))}/><div className="intro-moves"><strong>{level.moves}</strong> langkah untuk membuat keajaiban</div><p className="tip-text">{level.tip}</p><button className="primary" disabled={busy} onClick={onStart}><Play size={18} fill="currentColor"/>{busy?'Menyiapkan level…':'Mulai level'}</button><small className="modal-footnote">Booster bisa dipakai selama permainan.</small></>}
 {modal==='pause'&&<PauseMenu onResume={()=>{onOpen(null);audio?.resume();}} onRetry={onRetry} onMap={onQuit} onSettings={()=>onOpen('settings')}/>}
 {modal==='settings'&&<><span className="modal-emblem"><Settings/></span><span className="eyebrow">JUST THE WAY YOU LIKE IT</span><h2>Pengaturan</h2><div className="settings-list">{([{key:'music',label:'Musik',icon:Music},{key:'sfx',label:'Efek suara',icon:Volume2},{key:'reducedMotion',label:'Kurangi animasi',icon:Sparkles}] as const).map(({key:field,label,icon:Icon})=><label className="setting-row" key={field}><span><Icon size={19}/>{label}</span><input type="checkbox" className="switch" checked={player.settings[field]} onChange={e=>{audio?.unlock();setting(field,e.target.checked);}}/></label>)}<label className="volume-row"><span>Volume <strong>{Math.round(player.settings.volume*100)}%</strong></span><input type="range" min="0" max="1" step=".05" value={player.settings.volume} onChange={e=>setting('volume',Number(e.target.value))}/></label></div><button className="primary" onClick={onClose}><Check size={18}/>Selesai</button></>}
 {modal==='win'&&frame&&<WinModal score={frame.score} best={player.highScores[level.id]??frame.score} stars={starsFor(frame.score,level.stars)} last={level.id===100} onNext={onNext} onRetry={onStart} onMap={onMap}/>}
 {modal==='lose'&&frame&&<LoseModal objectives={frame.objectives} onRetry={onStart} onMap={onMap}/>}
 {modal==='quit'&&<><Heart className="result-heart"/><h2>Berhenti sebentar?</h2><p>Progres level ini akan diulang dan kamu kehilangan 1 nyawa.</p><div className="modal-actions"><button className="primary" onClick={()=>onOpen(null)}>Lanjut bermain</button><button className="secondary" onClick={onConfirmQuit}>{quitTarget==='retry'?'Ulangi level':'Kembali ke map'}</button></div></>}
 {modal==='error'&&<><CloudOff className="result-heart"/><h2>Oops, candy tersangkut.</h2><p>Level ini bisa diulang tanpa kehilangan nyawa.</p><button className="primary" onClick={onStart}>Ulangi level</button></>}
 {modal==='lives'&&<><Heart className="result-heart" fill="currentColor"/><span className="eyebrow">A LITTLE TIME TO RECHARGE</span><h2>{player.lives===5?'Penuh energi!':`${player.lives} nyawa tersisa`}</h2><div className="lives-row">{[1,2,3,4,5].map(n=><Heart key={n} fill={n<=player.lives?'currentColor':'none'} className={n<=player.lives?'filled':''}/>)}</div><p>{player.lives===5?'Semua nyawamu sudah terisi. Petualangan menantimu.':`Nyawa berikutnya terisi sekitar ${refillMinutes} menit lagi. Satu nyawa pulih setiap 30 menit.`}</p><button className="primary" onClick={onClose}>Mengerti</button></>}
 {modal==='daily'&&<><span className="daily-gift"><Gift/></span><span className="eyebrow">A LITTLE SOMETHING FOR YOU</span><h2>Your daily treat</h2><p>Sedikit hadiah untuk membuat harimu<br/>lebih manis. Datang lagi besok!</p><div className="daily-rewards"><span><Coins/><strong>100</strong><small>KOIN</small></span><span><Sparkles/><strong>1</strong><small>HAMMER</small></span></div><button className="primary" disabled={player.lastReward===dayKey()} onClick={claimDaily}>{player.lastReward===dayKey()?<><Check size={18}/>Sudah diambil hari ini</>:<>Ambil hadiah<Gift size={18}/></>}</button></>}
 {modal==='help'&&<><span className="modal-emblem"><Lightbulb/></span><span className="eyebrow">SMALL MATCHES. BIG POSSIBILITIES.</span><h2>A little candy guide</h2><div className="help-list"><div><span>01</span><p><strong>Tukar & cocokkan</strong>Tap dua candy bersebelahan atau swipe satu langkah. Cocokkan 3 bentuk sama. Swap gagal tidak memakai langkah.</p></div><div><span>02</span><p><strong>Ciptakan special candy</strong>4 lurus → striped. Bentuk T/L → wrapped. 5 lurus → color bomb. Tukar dua special untuk combo besar!</p></div><div><span>03</span><p><strong>Selesaikan semua target</strong>Pecahkan es dengan match di bawahnya. Match di samping kotak, batu, cokelat, dan gembok. Bawa kiriman bintang ke bawah.</p></div><div><span>04</span><p><strong>Main dengan nyaman</strong>Pakai booster saat perlu. Keyboard: arah untuk memilih tile, Enter untuk memilih candy, Shift + arah untuk swap.</p></div></div><button className="primary" onClick={onClose}>Let’s make magic!</button></>}
 {modal==='profile'&&<><span className="profile-avatar"><UserRound/></span><span className="eyebrow">HELLO, SWEET EXPLORER</span><h2>Your little world</h2><div className="profile-stats"><span><strong>{player.unlockedLevels}</strong>LEVEL</span><span><strong>{Object.values(player.stars).reduce((a,b)=>a+b,0)}</strong>BINTANG</span><span><strong>{fmt(Object.values(player.highScores).reduce((a,b)=>a+b,0))}</strong>BEST TOTAL</span></div><form onSubmit={e=>{e.preventDefault();const name=username.trim();if(name.length<2){notify('Nama minimal 2 karakter.');return;}updatePlayer(p=>({...p,username:name.slice(0,24),updatedAt:Date.now()}));notify('Nama pemain disimpan.');}}><label className="field-label" htmlFor="username">Nama pemain</label><div className="input-row"><input id="username" required minLength={2} maxLength={24} value={username} onChange={e=>setUsername(e.target.value)}/><button className="secondary" type="submit" aria-label="Simpan nama"><Check size={18}/></button></div></form><div className="auth-section">{sessionEmail?<><p className="session-email">Terhubung sebagai {sessionEmail}</p><button className="secondary" onClick={()=>void signOut().then(()=>{onSignOut();notify('Keluar dari akun. Mode tamu tetap bisa dimainkan.');}).catch(()=>notify('Belum berhasil keluar. Coba lagi.'))}><LogOut size={16}/>Keluar</button></>:database()?<> <div className="auth-tabs"><button type="button" className={`auth-tab ${authMode==='login'?'active':''}`} onClick={()=>setAuthMode('login')}>Masuk</button><button type="button" className={`auth-tab ${authMode==='register'?'active':''}`} onClick={()=>setAuthMode('register')}>Daftar</button></div>
<form onSubmit={async e=>{e.preventDefault();setAuthBusy(true);try{if(authMode==='register'){if(password.length<6){notify('Password minimal 6 karakter.');return;}await signUp(email,password,username);notify('Akun dibuat! Periksa email untuk verifikasi bila diminta.');setAuthMode('login');}else{await signInWithPassword(email,password);notify('Selamat datang kembali!');}}catch(error){notify(error instanceof Error?error.message:'Login belum berhasil.');}finally{setAuthBusy(false);}}}><p>{authMode==='register'?'Buat akun untuk menyimpan progres lintas perangkat.':'Masuk untuk menyimpan progres lintas perangkat.'}</p>{authMode==='register'&&<><label className="field-label" htmlFor="auth-username">Nama pemain</label><input id="auth-username" required minLength={2} maxLength={24} value={username} onChange={e=>setUsername(e.target.value)} placeholder="Nama manismu"/></>}<label className="field-label" htmlFor="email">Email</label><input id="email" type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="kamu@email.com"/><label className="field-label" htmlFor="password">Password</label><input id="password" type="password" required minLength={6} autoComplete={authMode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimal 6 karakter"/><button className="secondary" type="submit" disabled={authBusy}><Mail size={17}/>{authBusy?'Memproses…':authMode==='register'?'Buat akun':'Masuk'}</button></form>
<div className="auth-divider"><span>atau</span></div>
<form onSubmit={async e=>{e.preventDefault();setAuthBusy(true);try{await signIn(email);notify('Link masuk sudah dikirim. Periksa emailmu.');}catch(error){notify(error instanceof Error?error.message:'Login belum berhasil.');}finally{setAuthBusy(false);}}}><button className="text-button" type="submit" disabled={authBusy}><Mail size={15}/>{authBusy?'Mengirim…':'Kirim link masuk tanpa password'}</button></form></>:<p className="local-note"><ShieldCheck size={17}/>Kamu bermain sebagai tamu. Progres tersimpan di perangkat ini. Login online belum tersedia.</p>}</div></>}
 {modal==='leaderboard'&&<><Trophy className="result-trophy"/><span className="eyebrow">A LITTLE FRIENDLY COMPETITION</span><h2>Sweetest explorers</h2><p>{leaderboardStatus||'Skor terbaik dari petualangan terverifikasi.'}</p>{leaderboard.length>0&&<div className="leaderboard-table"><div className="leaderboard-head"><span>#</span><span>PEMAIN</span><span>SKOR</span><span>★</span></div>{leaderboard.map((entry,i)=><div className="leaderboard-row" key={`${entry.username}-${i}`}><span>{i+1}</span><span><strong>{entry.username}</strong><small>Level {entry.level}</small></span><strong>{fmt(entry.score)}</strong><span>{entry.stars}</span></div>)}</div>}<div className="personal-record"><UserRound/><span><strong>{player.username}</strong><small>Rekor di perangkat ini · Level {player.unlockedLevels}</small></span><strong>{fmt(Object.values(player.highScores).reduce((a,b)=>a+b,0))}</strong></div><button className="primary" onClick={onClose}>Kembali bermain</button></>}
 </Modal>;
}
