'use client';
import { useEffect,useRef,useState } from 'react';
import { key,type Position } from '@/types/Candy';
import type { Frame } from '@/game/Game';
import { CANDIES } from '@/config/candies';
import { BLOCKERS } from '@/config/blockers';
import { ParticleManager } from '@/game/ParticleManager';
import CandyVisual from './CandyVisual';
export default function GameBoard({frame,busy,hint,selected,onSelect,onSwap,reducedMotion,booster}:{frame:Frame;busy:boolean;hint:Position[];selected:Position|null;onSelect:(p:Position)=>void;onSwap:(a:Position,b:Position)=>void;reducedMotion:boolean;booster:string|null}){
 const boardRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),particles=useRef<ParticleManager|null>(null);
 const gesture=useRef<{p:Position;x:number;y:number;id:number}|null>(null);const [dragging,setDragging]=useState(false);
 useEffect(()=>{if(canvasRef.current)particles.current=new ParticleManager(canvasRef.current);return()=>particles.current?.destroy();},[]);
 useEffect(()=>{if(frame.phase==='MATCHING'&&!reducedMotion)for(const k of frame.hits){const [r,c]=k.split(',').map(Number);particles.current?.burst((c+.5)*60,(r+.5)*60,CANDIES[frame.board[r][c]?.candy?.color??0].color);}},[frame,reducedMotion]);
 const cells=frame.board.flatMap((row,r)=>row.flatMap((cell,c)=>cell?[{cell,r,c}]:[]));
 return <div className={`board-frame ${frame.phase==='SHUFFLING'?'shuffling':''} ${frame.chain>3&&frame.phase==='MATCHING'?'big-combo':''} ${booster?'booster-active':''} ${frame.phase==='BONUS_ACTIVATING'?'activate-pulse':''} ${frame.phase==='CONVERTING_MOVES'?'converting':''}`}><div ref={boardRef} className="board" role="grid" aria-label="Papan candy 9 kali 9" aria-busy={busy} onPointerMove={e=>{if(gesture.current&&Math.hypot(e.clientX-gesture.current.x,e.clientY-gesture.current.y)>12)setDragging(true);}} onPointerCancel={()=>{gesture.current=null;setDragging(false);}}>
 {cells.map(({r,c,cell})=><div className={`tile ${(r+c)%2?'alternate':''} ${cell.blocker?'has-blocker':''}`} style={{transform:`translate3d(${c*100}%, ${r*100}%, 0)`,left:0,top:0}} key={`tile-${r}-${c}`}/>)}
 {cells.filter(({cell})=>cell.candy).map(({r,c,cell})=>{const p={r,c},candy=cell.candy!,chosen=selected&&key(selected)===key(p),hinted=hint.some(h=>key(h)===key(p));return <button key={candy.id} data-cell={key(p)} className={`candy-cell ${chosen?'selected':''} ${hinted?'hinted':''} ${frame.phase==='MATCHING'&&frame.hits.includes(key(p))?'matched':''} ${frame.phase==='FALLING'?'falling':''}`} style={{transform:`translate3d(${c*100}%, ${r*100}%, 0)`,left:0,top:0}} role="gridcell" aria-selected={!!chosen} aria-label={`${candy.item?'Kiriman bintang':CANDIES[candy.color].name}${candy.special?`, ${candy.special}`:''}${cell.blocker?`, ${BLOCKERS[cell.blocker.kind].name}, ${cell.blocker.hp} lapisan`:''}, baris ${r+1} kolom ${c+1}`} aria-disabled={busy} onPointerDown={e=>{if(busy||e.button!==0)return;e.preventDefault();e.currentTarget.focus({preventScroll:true});gesture.current={p,x:e.clientX,y:e.clientY,id:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={e=>{const g=gesture.current;gesture.current=null;setDragging(false);if(!g||busy||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;const threshold=Math.max(12,(boardRef.current?.clientWidth??320)/9*.25);if(!booster&&Math.max(Math.abs(dx),Math.abs(dy))>threshold){const to={r:g.p.r+(Math.abs(dy)>Math.abs(dx)?Math.sign(dy):0),c:g.p.c+(Math.abs(dx)>=Math.abs(dy)?Math.sign(dx):0)};onSwap(g.p,to);}else onSelect(g.p);}} onKeyDown={e=>{if(busy)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(p);}const delta:Record<string,number[]>={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};if(delta[e.key]){e.preventDefault();const [dr,dc]=delta[e.key],to={r:r+dr,c:c+dc};if(e.shiftKey)onSwap(p,to);else boardRef.current?.querySelector<HTMLButtonElement>(`[data-cell="${key(to)}"]`)?.focus();}}}>
 <CandyVisual candy={candy}/></button>;})}
 {cells.filter(({cell})=>cell.blocker).map(({r,c,cell})=>{const b=cell.blocker!;return <button key={`block-${r}-${c}`} className={`blocker blocker-${b.kind} ${b.hp<b.maxHp?'cracked':''}`} style={{transform:`translate3d(${c*100}%, ${r*100}%, 0)`,left:0,top:0}} tabIndex={['ice','lock'].includes(b.kind)?-1:0} aria-label={`${BLOCKERS[b.kind].name}, ${b.hp} lapisan, baris ${r+1} kolom ${c+1}`} onClick={()=>{if(!busy)onSelect({r,c});}}><img src={`/assets/optimized/blockers/${b.kind}.webp`} alt="" draggable={false}/>{b.maxHp>1&&<span className="blocker-hp">{Array.from({length:b.hp},()=> '•').join('')}</span>}</button>;})}
 {frame.phase==='MATCHING'&&cells.filter(({r,c,cell})=>cell.candy?.special&&frame.hits.includes(key({r,c}))).map(({r,c,cell})=><div aria-hidden="true" key={`effect-${r}-${c}`} className={`special-effect effect-${cell.candy!.special}`} style={{'--effect-x':`${(c+.5)/9*100}%`,'--effect-y':`${(r+.5)/9*100}%`} as React.CSSProperties}><i/><b/></div>)}
 {frame.burstAt&&(()=>{const [r,c]=frame.burstAt.split(',').map(Number);const color=['#f283a9','#5fa8e8','#f2c14b','#7fc47f','#b577d9','#f08653'][frame.board[r]?.[c]?.candy?.color??0]??'#f7c9ec';return <div key={`burst-${frame.burstAt}-${frame.score}`} className="light-burst" style={{transform:`translate3d(${c*100}%, ${r*100}%, 0)`,left:0,top:0,'--burst-color':color} as React.CSSProperties}><i/><b/></div>;})()}
 {frame.finale&&frame.bonusText&&<div className="finale-banner" aria-hidden="true"><div><h3>{frame.phase==='FINALE_START'?'✨ SWEET FINALE! ✨':frame.bonusText}</h3><p>{frame.phase==='FINALE_START'?'Objective complete — bonus moves!':`${frame.moves} moves remaining`}</p></div></div>}
 {frame.burstAt&&frame.bonusText&&frame.phase==='CONVERTING_MOVES'&&(()=>{const [r,c]=frame.burstAt.split(',').map(Number);return <span key={`float-${r}-${c}`} className="float-bonus" style={{left:`${(c+.5)/9*100}%`,top:`${(r+.5)/9*100}%`}} aria-hidden="true">{frame.bonusText}</span>;})()}
 <canvas width={540} height={540} ref={canvasRef} className="particles" aria-hidden="true"/>
 {(frame.phase==='MATCHING'&&frame.message)&&<div key={`${frame.score}-${frame.chain}`} className={`combo-popup ${frame.message.includes('Magic')?'special-popup':''}`} aria-hidden="true">{frame.message}<small>{frame.chain>1?`Combo ?${frame.chain}`:'Perfect match'}</small></div>}
 {frame.phase==='SHUFFLING'&&<div className="shuffle-message">{frame.message}</div>}
 </div><span className="sr-only" aria-live="polite">{frame.phase==='IDLE'?`${frame.moves} langkah tersisa. Skor ${frame.score}.`:''}</span><span className="board-corner" aria-hidden="true">✦</span>{dragging&&<span className="sr-only">Menggeser candy</span>}</div>;
}
