import { useEffect,useRef } from 'react';
import { Flower2,Cookie,Leaf,Snowflake,Crown,CloudSun,Rainbow,Castle,Gem,Trophy,ChevronLeft,Star } from 'lucide-react';
import { LEVELS,WORLDS } from '@/levels';
import type { Player } from '@/types/Player';
import LevelButton from './LevelButton';
const ICONS:Record<string,React.ComponentType<{size?:number}>>={flower:Flower2,cookie:Cookie,leaf:Leaf,snow:Snowflake,crown:Crown,star:CloudSun,rainbow:Rainbow,gem:Gem,trophy:Trophy};
const DECOR_LEFT=['purple-flower','orange-circle','green-square','blue-star','yellow-drop','red-heart','blue-star','purple-flower','green-square','yellow-drop'];
const DECOR_RIGHT=['red-heart','yellow-drop','purple-flower','blue-star','red-heart','orange-circle','green-square','yellow-drop','orange-circle','red-heart'];
export default function LevelMap({player,onSelect,onHome}:{player:Player;onSelect:(id:number)=>void;onHome:()=>void}){
 const currentRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{currentRef.current?.scrollIntoView({block:'center',behavior:'smooth'});},[]);
 return <section className="map-page"><div className="page-heading"><button className="icon-button" onClick={onHome} aria-label="Kembali ke home"><ChevronLeft/></button><div><span className="eyebrow">ONE SWEET STEP AT A TIME</span><h1>Your candy adventure</h1></div><span className="total-stars"><Star fill="currentColor" size={18}/>{Object.values(player.stars).reduce((a,b)=>a+b,0)} / 300</span></div><div className="world-map">{WORLDS.map((world,w)=>{const Icon=ICONS[world.icon]??Gem;return <section className={`world world-${w}`} key={world.name} style={{'--world-color':world.color} as React.CSSProperties}><div className="world-title"><span className="world-icon"><Icon/></span><div><span className="eyebrow">WORLD 0{w+1}</span><h2>{world.name}</h2><p>{world.subtitle}</p></div></div><div className="world-levels">{LEVELS.filter(l=>l.world===w).map((level,i)=><div className={`level-cell ${level.id===player.currentLevel?'current-stop':''}`} key={level.id} ref={level.id===player.currentLevel?currentRef:undefined}><LevelButton id={level.id} unlocked={level.id<=player.unlockedLevels} current={level.id===player.currentLevel} stars={player.stars[level.id]??0} onSelect={()=>onSelect(level.id)}/></div>)}</div><img className="map-decoration decor-left" src={`/assets/optimized/candies/${DECOR_LEFT[w]}.webp`} alt=""/><img className="map-decoration decor-right" src={`/assets/optimized/candies/${DECOR_RIGHT[w]}.webp`} alt=""/></section>;})}</div><p className="map-end">Every little match is a little magic. ✦</p></section>;}
